# Generated by Django 3.2.9 on 2021-11-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellrecord',
            name='customer_phone',
            field=models.CharField(max_length=12),
        ),
    ]
